cancer_herbs/cancer_herbs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('herbs/', include('herbs.urls')),
]

cancer_herbs/herbs/urls.py
# from django.urls import path

# from . import views

# urlpatterns = [
#     path('', views.HomePageView, name='home'),
#     path('results/', views.ResultsPageView, name='results'),
#     path('detail/<int:pk>/', views.DetailPageView, name='detail'),
# ]
from django.urls import path
from .views import HomePageView, PlantDetailView, ChemicalDetailView
app_name = 'herbs'

urlpatterns = [
    path('home', HomePageView.as_view(), name='home'),
    path('report/<int:pk>/', PlantDetailView.as_view(), name='report'),
    path('chemical/<int:chemical_id>/', ChemicalDetailView.as_view(), name='chemical_detail')
]

cancer_herbs/herbs/models.py
from django.shortcuts import render
from django.db import models

#Define Models
class Chemical(models.Model):
    chemical_id = models.IntegerField(primary_key=True)
    inchi_value = models.CharField(max_length=10000, null=True)
    pubchem_cid = models.CharField(max_length=1000, null=True)
    chembl_id = models.CharField(max_length=50, null=True)

class Plant(models.Model):

    class Meta:
        ordering = ['plant_id']

    plant_id = models.IntegerField(primary_key=True)
    taxonomy = models.CharField(max_length=5000, null=True)
    ncbi_species_id = models.CharField(max_length=1000, null=True)
    ncbi_subspecies_id = models.CharField(max_length=1000, null=True)

class XRef(models.Model):
    xref_id = models.IntegerField(primary_key=True)
    chemical_id = models.ForeignKey(Chemical, on_delete=models.CASCADE, related_name='xrefs')
    plant_id = models.ForeignKey(Plant, on_delete=models.CASCADE, related_name='xrefs')
    referenceCleanedDoi = models.CharField(max_length=5000, null=True)
    referenceCleanedTitle = models.CharField(max_length=5000, null=True)
    referenceCleanedPmcid = models.CharField(max_length=1000, null=True)
    referenceCleanedPmid = models.CharField(max_length=1000, null=True)

class Drug(models.Model):

    class Meta:
        db_table = 'Drugs'
        
    drug_pair_id = models.IntegerField(primary_key=True)
    chemical_id = models.ForeignKey(Chemical, on_delete=models.CASCADE, related_name='drugs', db_column='chemical_id')
    drug_chembl_id = models.CharField(max_length=200, null=True)
    tanimoto_similarity = models.FloatField(null=True)
    target_chembl_id = models.CharField(max_length=200, null=True)
    target_gene_id = models.CharField(max_length=100, null=True)


class Target(models.Model):
    target_gene_id = models.CharField(max_length=255, primary_key=True)
    target_synonyms = models.TextField(null=True)
    target_description = models.TextField(null=True)
    target_other_designations = models.TextField(null=True)
    target_ncbi_id = models.CharField(max_length=100, null=True)
    target_entrez_url = models.URLField(null=True)
    target_ensembl_id = models.CharField(max_length=100, null=True)
    target_ensembl_url = models.URLField(null=True)
    target_chembl_id = models.CharField(max_length=100, null=True)
    target_chembl_url = models.URLField(null=True)
    target_uniprot_id = models.CharField(max_length=100, null=True)
    target_cbioportal_url = models.URLField(null=True)
    target_ncigenomics_url = models.URLField(null=True)
    target_ncitargetdiscovery_url = models.URLField(null=True)
    target_cosmic_url = models.URLField(null=True)
    target_cancergeneticsweb_url = models.URLField(null=True)
    target_depmap_url = models.URLField(null=True)
    target_cansar_url = models.URLField(null=True)

cancer_herbs/herbs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Plant, Chemical, XRef, Drug
from django.core.paginator import EmptyPage, PageNotAnInteger


class HomePageView(ListView):
    model = Plant
    template_name = 'herbs/home.html'
    context_object_name = 'plants'
    ordering = ['plant_id']

    paginate_by = 30  # <--- specify the number of items per page


    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        search_type = self.request.GET.get('search_type')
        search_field = self.request.GET.get('search_field')
        
        if search_type == 'Chemical' and search_field in ['inchi_value', 'pubchem_cid']:
            chemical = Chemical.objects.filter(**{search_field: query}).first()
            if chemical:
                return redirect('herbs:chemical_detail', chemical_id=chemical.chemical_id)
        
        return super().get(request, *args, **kwargs)



    def get_queryset(self):
        query = self.request.GET.get('q')
        search_type = self.request.GET.get('search_type')
        search_field = self.request.GET.get('search_field')

        if search_type and search_field:
            if search_type == 'Plant':
                if search_field == 'ncbi_species_id':
                    return Plant.objects.filter(
                        Q(ncbi_species_id__icontains=query) | 
                        Q(ncbi_subspecies_id__icontains=query)
                    )
                elif search_field == 'taxonomy':
                    return Plant.objects.filter(taxonomy__icontains=query)
            
            # If the user selects an invalid combination, show no results
            return Plant.objects.none()

        # If we reach here, no search parameters were provided
        # Returning all plants as a default behavior
        return Plant.objects.all()






    

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        
        # Get the current page number from the paginator
        page = context['page_obj'].number

        # Calculate the start and end pages for the fixed range
        start_page = ((page - 1) // 10) * 10 + 1
        end_page = start_page + 9

        # Ensure end_page doesn't exceed the maximum number of pages
        end_page = min(end_page, context['paginator'].num_pages)
        
        # Create the range of page numbers
        context['page_range'] = range(start_page, end_page + 1)
        
        return context




class PlantDetailView(DetailView):
    model = Plant
    template_name = 'herbs/report.html'
    context_object_name = 'plant'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        plant = self.get_object()

        # Fetch related chemicals for the plant
        xrefs = XRef.objects.filter(plant_id=plant).select_related('chemical_id')

        # For each xref (which represents a chemical), fetch the count of associated drugs
        for xref in xrefs:
            xref.similar_drug_count = Drug.objects.filter(chemical_id=xref.chemical_id.chemical_id).count()

        # Sort the xrefs based on the similar_drug_count in descending order
        xrefs_sorted = sorted(xrefs, key=lambda x: x.similar_drug_count, reverse=True)

        # Build a list of unique chemicals and xrefs preserving the order
        seen_chemicals = set()
        unique_chemicals = []
        unique_xrefs = []
        for xref in xrefs_sorted:
            if xref.chemical_id not in seen_chemicals:
                seen_chemicals.add(xref.chemical_id)
                unique_chemicals.append(xref.chemical_id)
                unique_xrefs.append(xref)

        context['chemicals'] = unique_chemicals
        context['xrefs'] = unique_xrefs
        return context





class ChemicalDetailView(DetailView):
    model = Chemical
    template_name = 'herbs/chemical_detail.html'
    context_object_name = 'chemical'
    pk_url_kwarg = 'chemical_id'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        chemical_id = self.get_object()

        # Fetch the plants this chemical is found in
        xrefs = XRef.objects.filter(chemical_id=chemical_id).select_related('plant_id')
        plants = list(set([xref.plant_id for xref in xrefs]))  # Using set to ensure distinct plants

        # Fetch similar drugs
        similar_drugs = Drug.objects.filter(chemical_id=chemical_id).order_by('-tanimoto_similarity')

        context['plants'] = plants
        context['similar_drugs'] = similar_drugs

        return context

cancer_herbs/herbs/templates/herbs/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Cancer Herbs Database</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'herbs/styles2.css' %}">
</head>
<body>
    <header>
        <h1><a href="{% url 'herbs:home' %}">Cancer Herbs Database</a></h1>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

cancer_herbs/herbs/templates/herbs/chemical_detail.html
{% extends 'herbs/base.html' %}

{% block content %}
    <h1>Chemical ID: {{ chemical.chemical_id }}</h1> <!-- Displaying the Chemical ID as the title -->

    <!-- Separate card for InChI Value -->
    <div class="card">
        <h3>InChI Value:</h3>
        <p>{{ chemical.inchi_value }}</p>
        
        {% if chemical.chembl_id %}
            <h3>ChEMBL ID:</h3>
            <p>{{ chemical.chembl_id }}</p>
        {% endif %}
    
    </div>

    <!-- Section for Plants -->
    <div class="card">
        <h2>Found in:</h2>
        <ul>
        {% for plant in plants %}
            <li><a href="{% url 'herbs:report' plant.plant_id %}">{{ plant.taxonomy }}</a></li>

        {% endfor %}
        </ul>
    </div>

    <!-- Section for Similar Drugs -->
    <div class="card">
        <h2>Similar Drugs:</h2>
        <table class="drugs-table"> <!-- Adding a class for better styling -->
            <thead>
                <tr>
                    <th>Drug ID</th>
                    <th>Tanimoto Coefficient</th>
                    <th>Target Gene Name</th>
                </tr>
            </thead>
            <tbody>
            {% for drug in similar_drugs %}
                <tr>
                    <td><a href="https://www.ebi.ac.uk/chembl/compound_report_card/{{ drug.drug_chembl_id }}/" target="_blank">{{ drug.drug_chembl_id }}</a></td>
                    <td>{{ drug.tanimoto_similarity }}</td>
                    <td><a href="https://www.ebi.ac.uk/chembl/target_report_card/{{ drug.target_chembl_id }}/" target="_blank">{{ drug.target_gene_id }}</a></td>                    
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

cancer_herbs/herbs/templates/herbs/home.html
{% extends 'herbs/base.html' %}

{% block content %}
    <!-- Search Bar -->
    <div class="search-bar">
        <form method="GET" action="{% url 'herbs:home' %}">
            <!-- Dropdown for selecting Plant or Chemical -->
            <select id="searchType" name="search_type" onchange="updateFieldsDropdown()">
                <option value="Plant">Plant</option>
                <option value="Chemical">Chemical</option>
            </select>

            <!-- Dropdown for selecting the specific search field -->
            <select id="searchField" name="search_field">
            <option value="ncbi_species_id">NCBI ID</option>
            <option value="taxonomy">Taxonomy</option>
            </select>
            
            <!-- Search Input -->
            <input id="searchInput" class="search-input" type="text" name="q" value="{{ request.GET.q }}">
            <input class="search-button" type="submit" value="Search">
        </form>
    </div>

    <!-- Plant Listings -->
    <ul class="plant-list">
        {% for plant in page_obj %}
            <li class="plant-item">
                <a href="{% url 'herbs:report' plant.plant_id %}">{{ plant.taxonomy }}</a>
            </li>
        {% empty %}
            <li>No plants found.</li>
        {% endfor %}
    </ul>


    <!-- Pagination -->
    <div class="pagination">
        <!-- Previous Range Button -->
        {% if page_obj.number > 10 %}
            <a href="?page={{ page_obj.number|add:"-1" }}"><<</a>
        {% endif %}
        
        <!-- Individual Page Numbers -->
        {% for page_num in page_range %}
            <a href="?page={{ page_num }}"
               class="{% if page_num == page_obj.number %}current{% endif %}">
                {{ page_num }}
            </a>
        {% endfor %}
        
        <!-- Next Range Button -->
        {% if page_obj.number <= paginator.num_pages|add:"-9" %}
            <a href="?page={{ page_obj.number|add:"1" }}">>></a>
        {% endif %}
    </div>
    

    <!-- JavaScript to Update Fields Dropdown -->
    <script>
        function updateFieldsDropdown() {
            var searchType = document.getElementById("searchType").value;
            var searchField = document.getElementById("searchField");
            searchField.innerHTML = "";  // Clear existing options

            if (searchType === "Plant") {
                var options = ["ncbi_species_id", "taxonomy"];
            } else {
                var options = ["inchi_value", "pubchem_cid"];
            }

            for (var i = 0; i < options.length; i++) {
                var opt = options[i];
                var el = document.createElement("option");
                el.textContent = opt;
                el.value = opt;
                searchField.appendChild(el);
            }
        }

        // Initialize the fields dropdown
        window.onload = function() {
            updateFieldsDropdown();
        };
    </script>
{% endblock %}

cancer_herbs/herbs/templates/herbs/report.html
{% extends 'herbs/base.html' %}

{% block content %}
    <div class="plant-info">
        <h2>{{ plant.taxonomy }}</h2>
        <p>NCBI Species ID: <a href="https://www.ncbi.nlm.nih.gov/taxonomy/?term={{plant.ncbi_species_id}}" target="_blank">{% if plant.ncbi_species_id %}{{ plant.ncbi_species_id }}{% else %}Not available{% endif %}</a></li>
        <p>NCBI Subspecies ID: <a href="https://www.ncbi.nlm.nih.gov/taxonomy/?term={{plant.ncbi_subspecies_id}}" target="_blank">{% if plant.ncbi_subspecies_id %}{{ plant.ncbi_subspecies_id }}{% else %}Not available{% endif %}</a></li>
    </div>
    <h3>Chemicals:</h3>
    {% for xref in xrefs %}
        <div class="card">
            <h4>
                <a href="{% url 'herbs:chemical_detail' xref.chemical_id.chemical_id %}">{{ xref.chemical_id.chemical_id }}</a>
                <!-- Check the value of similar_drug_count and assign the corresponding CSS class -->
                <span class="{% if xref.similar_drug_count == 0 %}red-text{% else %}green-text{% endif %}">{{ xref.similar_drug_count }} similar drugs</span>
            </h4>
            <ul>
                <li>{% if xref.chemical_id.inchi_value %}{{ xref.chemical_id.inchi_value }}{% else %}Not available{% endif %}</li>
                <li>PubChem CID: <a href="https://pubchem.ncbi.nlm.nih.gov/#query={{xref.chemical_id.pubchem_cid}}" target="_blank">{% if xref.chemical_id.pubchem_cid %}{{ xref.chemical_id.pubchem_cid }}{% else %}Not available{% endif %}</a></li>
                <li>ChEMBL ID: <a href="https://www.ebi.ac.uk/chembl/compound_report_card/{{xref.chemical_id.chembl_id}}" target="_blank">{% if xref.chemical_id.chembl_id %}{{ xref.chemical_id.chembl_id }}{% else %}Not available{% endif %}</a></li>
                <li>Reference DOI: <a href="https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q={{ xref.referenceCleanedDoi }}" target="_blank">{% if xref.referenceCleanedDoi %}{{ xref.referenceCleanedDoi }}{% else %}Not available{% endif %}</a></li>

            </ul>
        </div>
    {% empty %}
        <p>No chemicals found.</p>
    {% endfor %}
{% endblock %}